<a href="https://colab.research.google.com/github/KweonTJ/Artifical_Intelligence-ML-NN-/blob/main/1.numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy 실습

NumPy는 Python에서 수치 계산을 위한 핵심 라이브러리입니다.  
이 실습에서는 NumPy의 기본적인 배열 생성, 연산, 인덱싱 등을 학습합니다.

**참고자료:** https://numpy.org/doc/stable/user/quickstart.html

**학번 :**  2023042028\
**이름 :** 권택주

---
## 1. 배열 생성 (Creation) #1

Python 리스트와 NumPy 배열의 차이점을 이해합니다.

- Python 리스트: `[1, 2, 3]`
- NumPy 배열: `np.array([1, 2, 3])`

NumPy 배열은 인덱싱 시 `n2[1, 0]` 형태로 접근할 수 있습니다.

---

In [2]:
import numpy as np

## Python 리스트
x1 = [1, 2, 3, 4, 5, 6]
print(x1)

x2 = [[1, 2, 3], [4, 5, 6]]
print(x2)
print(x2[1][0])  # 리스트는 이중 인덱싱 필요

## NumPy 배열로 변환
# IMPLEMENT HERE: x1을 numpy 배열로 변환하여 n1에 저장하세요
n1 = np.array(x1)
print(n1)
print(n1[0])

# IMPLEMENT HERE: x2를 numpy 배열로 변환하여 n2에 저장하세요
n2 = np.array(x2)
print(n2)
print(n2[1, 0])  # NumPy는 콤마로 인덱싱 가능
print(n2[1][0])  # 이중 인덱싱도 가능

[1, 2, 3, 4, 5, 6]
[[1, 2, 3], [4, 5, 6]]
4
[1 2 3 4 5 6]
1
[[1 2 3]
 [4 5 6]]
4
4


---
## 2. 배열 생성 (Creation) #2

NumPy는 특정 값으로 초기화된 배열을 쉽게 생성할 수 있습니다.

- `np.zeros(shape)`: 0으로 채워진 배열
- `np.ones(shape)`: 1로 채워진 배열
- `np.empty(shape)`: 초기화되지 않은 배열 (빠른 생성)
- `dtype` 매개변수로 데이터 타입 지정 가능

---

In [3]:
import numpy as np

# IMPLEMENT HERE: 3x4 크기의 0으로 채워진 배열을 생성하세요
m1 = np.zeros((3,4))
print(m1)
print(m1.dtype)

# IMPLEMENT HERE: 3x4 크기의 1로 채워진 배열을 생성하세요
m2 = np.ones((3,4))
print(m2)
print(m2.dtype)

# dtype을 int16으로 지정한 ones 배열
m3 = np.ones((3, 4), dtype=np.int16)
print(m3)
print(m3.dtype)

# empty 배열 (초기화되지 않음 - 쓰레기 값 포함)
m4 = np.empty((3, 4))
print(m4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
int16
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


---
## 3. Reshape (배열 형태 변경)

`reshape()` 함수를 사용하여 배열의 형태를 변경할 수 있습니다.

- `np.arange(n)`: 0부터 n-1까지의 배열 생성
- `reshape(행, 열)`: 배열 형태 변경
- `reshape(행, -1)`: -1은 자동 계산

---

In [4]:
import numpy as np

## arange로 배열 생성
r1 = np.arange(6)
print(r1)

# IMPLEMENT HERE: r1을 2행 3열로 reshape하세요
r2 = r1.reshape(2,3)
print(r2)

# -1을 사용한 자동 계산 (2행, 열은 자동)
r3 = np.arange(6).reshape(2, -1)
print(r3)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]


---
## 4. 기본 연산 (Basic Operation)

NumPy 배열은 요소별(element-wise) 연산을 지원합니다.

- `+`, `-`, `*`, `/`: 요소별 연산
- `**`: 거듭제곱
- `@` 또는 `.dot()`: 행렬 곱셈

**주의:** `*`는 요소별 곱셈, `@`는 행렬 곱셈입니다.

---

In [6]:
import numpy as np

## 기본 연산 1: 요소별 연산
a = np.array([20, 30, 40, 50])
b = np.arange(4)

c1 = a - b
print("a:", a)
print("b:", b)
print("a - b:", c1)

c2 = b ** 2
print("b ** 2:", c2)

a: [20 30 40 50]
b: [0 1 2 3]
a - b: [20 29 38 47]
b ** 2: [0 1 4 9]


In [9]:
import numpy as np

## 기본 연산 2: 행렬 곱셈
A = np.array([1, 1, 0, 1]).reshape(2, 2)
B = np.array([2, 0, 3, 4]).reshape(2, 2)

print("A:")
print(A)
print("B:")
print(B)

# 요소별 곱셈
print("A * B (요소별 곱셈):")
print(A * B)

# IMPLEMENT HERE: @ 연산자를 사용하여 행렬 곱셈을 수행하세요
print("A @ B (행렬 곱셈):")
print(A @ B)
print(B @ A)

# IMPLEMENT HERE: dot 메서드를 사용하여 행렬 곱셈을 수행하세요
print("A.dot(B) (행렬 곱셈):")
print(A.dot(B))


A:
[[1 1]
 [0 1]]
B:
[[2 0]
 [3 4]]
A * B (요소별 곱셈):
[[2 0]
 [0 4]]
A @ B (행렬 곱셈):
[[5 4]
 [3 4]]
[[2 2]
 [3 7]]
A.dot(B) (행렬 곱셈):
[[5 4]
 [3 4]]


---
## 5. Stack (배열 쌓기)

여러 배열을 합칠 수 있습니다.

- `np.hstack()`: 수평으로 쌓기 (가로 방향)
- `np.vstack()`: 수직으로 쌓기 (세로 방향)
- `np.concatenate()`: axis를 지정하여 쌓기

---

In [11]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])
c = np.array([1, 1, 1, 1, 1])

# IMPLEMENT HERE: a와 b를 수평으로 쌓으세요 (hstack)
o1 = np.hstack((a,b))
print("hstack:", o1)

# IMPLEMENT HERE: a와 b를 수직으로 쌓으세요 (vstack)
o2 = np.vstack((a,b))
print("vstack:")
print(o2)

# a, b, c를 수직으로 쌓기
o3 = np.vstack((a, b, c))
print("vstack (a, b, c):")
print(o3)

# concatenate 사용 (axis=0은 세로 방향)
o4 = np.concatenate((a.reshape(1, -1), b.reshape(1, -1)), axis=0)
# o4 = np.concatenate((a,b), axis=0)
print("concatenate:")
print(o4)

print(a.reshape(1, -1).shape)

hstack: [ 1  2  3  4  5  6  7  8  9 10]
vstack:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
vstack (a, b, c):
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  1  1  1  1]]
concatenate:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(1, 5)


---
## 6. Copy (복사)

NumPy 배열의 슬라이싱은 기본적으로 **얕은 복사(shallow copy)**입니다.

- 얕은 복사: 원본과 메모리를 공유 (원본 변경 시 복사본도 변경)
- 깊은 복사: `.copy()` 메서드 사용 (독립적인 복사본 생성)

---

In [12]:
import numpy as np

x = np.arange(10).reshape(2, 5)
print("원본 x:")
print(x)

# 얕은 복사 (shallow copy)
print('\n=== 얕은 복사 ===')
x = np.arange(10).reshape(2, 5)
y = x[0:2, 0:3]
print("y (x의 일부분):")
print(y)

x[0, 0] = 2  # 원본 수정
print("x[0,0] = 2 후 y:")
print(y)  # y도 변경됨!

# 깊은 복사 (deep copy)
print('\n=== 깊은 복사 ===')
x = np.arange(10).reshape(2, 5)
y = x[0:2, 0:3].copy()  # .copy() 사용
print("y (x의 일부분, copy):")
print(y)

x[0, 0] = 2  # 원본 수정
print("x[0,0] = 2 후 y:")
print(y)  # y는 변경되지 않음

원본 x:
[[0 1 2 3 4]
 [5 6 7 8 9]]

=== 얕은 복사 ===
y (x의 일부분):
[[0 1 2]
 [5 6 7]]
x[0,0] = 2 후 y:
[[2 1 2]
 [5 6 7]]

=== 깊은 복사 ===
y (x의 일부분, copy):
[[0 1 2]
 [5 6 7]]
x[0,0] = 2 후 y:
[[0 1 2]
 [5 6 7]]


---
## 7. Indexing (인덱싱)

NumPy는 불리언 배열을 이용한 인덱싱을 지원합니다.

- `x > 5`: 각 요소가 5보다 큰지 여부를 불리언 배열로 반환
- `x[x > 5]`: 조건을 만족하는 요소만 선택

---

In [13]:
import numpy as np

x = np.array([2, 5, 1, 5, 9, 4, 1, 8, 3, 2])
print("원본 x:", x)

# IMPLEMENT HERE: x에서 5보다 큰 요소를 불리언 배열로 출력하세요
print("x > 5:")
print(x > 5)

# IMPLEMENT HERE: x에서 5보다 큰 요소만 선택하여 출력하세요
print("x[x > 5]:")
print(x[x > 5])

# 조건을 만족하지 않는 요소를 0으로 변경
x[x <= 5] = 0
print("x[x <= 5] = 0 후:", x)

원본 x: [2 5 1 5 9 4 1 8 3 2]
x > 5:
[False False False False  True False False  True False False]
x[x > 5]:
[9 8]
x[x <= 5] = 0 후: [0 0 0 0 9 0 0 8 0 0]


---
## 8. 성능 비교 (Performance Test)

NumPy를 사용하면 Python 리스트보다 훨씬 빠른 연산이 가능합니다.  
아래 코드에서 두 방법의 성능을 비교해봅시다.

---

In [14]:
import numpy as np

# 내적(dot product) 계산의 세 가지 방법
A = list(range(0, 10))
B = list(range(0, 10))

# 방법 1: for 루프 사용
result = 0
for a, b in zip(A, B):
    result += a * b
print("방법 1 (for loop):", result)

# 방법 2: np.dot 사용
result = np.dot(A, B)
print("방법 2 (np.dot):", result)

# 방법 3: @ 연산자 사용
A = np.array(A)
B = np.array(B)
print("방법 3 (@ 연산자):", A @ B)

방법 1 (for loop): 285
방법 2 (np.dot): 285
방법 3 (@ 연산자): 285


In [15]:
import numpy as np
import time

# 큰 배열에서의 성능 비교
A = list(range(0, 10000))
B = list(range(0, 10000))

# 방법 1: for 루프
result = 0
t0 = time.time()
# IMPLEMENT HERE: for 루프를 사용하여 A와 B의 내적을 계산하세요

t1 = time.time()
print(f'list (for loop): {(t1-t0)*1e3:.4f} ms')

# 방법 2: NumPy
A = np.array(A)
B = np.array(B)
t0 = time.time()
# IMPLEMENT HERE: NumPy의 @ 연산자를 사용하여 내적을 계산하세요

t1 = time.time()
print(f'numpy (@ operator): {(t1-t0)*1e3:.4f} ms')

list (for loop): 0.0272 ms
numpy (@ operator): 0.0269 ms


---
## 제출 안내

1. 모든 문제를 완성한 후, 코드 셀을 실행하여 결과를 확인하세요.
2. **제출 파일:**
   - `.ipynb` 파일
   - `.pdf` 파일 (파일 > 인쇄 > PDF로 저장)
3. 파일명: `lec02_numpy_학번_이름.ipynb`, `lec02_numpy_학번_이름.pdf`
4. LMS에 두 파일을 함께 제출하세요.

**주의:** 기한 내에 제출하지 않으면 감점이 있습니다.

---